#ifndef __PanelFrame__
#define __PanelFrame__

/**
@file
Subclass of baseFrame, which is generated by wxFormBuilder.
*/

#include "BaseFrame.h"

//// end generated include

/** Implementing baseFrame */
class PanelFrame : public baseFrame
{
	public:
		/** Constructor */
		PanelFrame( wxWindow* parent );
	//// end generated class members

};

#endif // __PanelFrame__
